### ISSUE TITLE
Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by dsv0010** [dsv0010/GESPRO_Practicas#11]
Anexo de la memoria En Open shift En Local

    RevPlammenManual de usuario.pdf
    Manual de usuario.pdf

**Comment by dzg0013** [comment]
adjunto Manual de usuario.pdf
Adjunto el anexo Manual de Usuario, en el que se explica cómo desplegar la instancia de SonarQube en local y en la plataforma OpenShift, cómo analizar un proyecto y la instalación de todas las herramientas utilizadas en los dos procesos anteriores.

**Comment by dsv0010** [comment]
-   attached RevPlammenManual de usuario.pdf

Revisión de manual de usuario. Complementarla con la entregada en papel.
