### ISSUE TITLE
Escaneo del histórico de versiones de un TFG

### ISSUE THREAD

**Issue by dsv0010** [dsv0010/GESPRO_Practicas#17]
Posibles candidatos PLQUIZ Gestor de trabajos fin de grado y/o máster

**Comment by dzg0013** [comment]
milestone cambiado a Creación de histórico de proyectos
incidencia asignada a   Plamen Petkov
descripcion editada

**Comment by dzg0013** [comment]
Creado el escaneo del histórico de versiones para los proyectos propuestos. Los resultados se pueden ver en los siguientes enlaces:
Gestor de trabajos fin de grado y/o máster: http://tfgqa-ubugii.rhcloud.com/overview?id=tfg.gestor.trabajos
PLQuiz: http://tfgqa-ubugii.rhcloud.com/overview?id=es.ubu.inf.tfg%3APLQuiz
