### ISSUE TITLE
 Elaboración de la documentación sobre el proyecto

### ISSUE THREAD

**Issue by dzg0013** [dsv0010/GESPRO_Practicas#6]
Elaboración de los apartados 1. Introducción y 2. Objetivos de la memoria del proyecto utilizando LaTeX y la plantilla proporcionada para el TFG.

**Comment by dsv0010** [comment]
- attached REV01_SonarQube_memoria.pdf

Adjunto la revisión de la memoria en un documento pdf con comentarios.

**Comment by dsv0010** [comment]
- attached BiblioCalidad.bib

Referencias bibliográfica en bibtex
