### ISSUE TITLE
Conceptos téoricos

### ISSUE THREAD

**Issue by dsv0010** [dsv0010/GESPRO_Practicas#9]
Calidad del software
    Medidas de código

Utilizar referencia Medición para la gestión en la ingeniería del software

Autor: José Javier Dolado Cosín; Luis Fernández Sanz Editorial: Madrid : RA-MA, ©2000. Edición/Formato: Print book : Español (spa)Ver todas las ediciones y todos los formatos Base de datos: WorldCat

**Comment by dzg0013** [comment]
adjunto memoria_conceptos_teoricos.pdf
Adjunto una versión provisional del apartado Conceptos Teóricos. Me he basado en tres libros diferentes para elaborar este apartado:
Libro Medición para la Gestión en la Ingeniería del Software que me has sugerido
Libro Software Engineering 9ª Edición - Sommerville
Libro Software Engineering: A practitioner's approach - Pressman
Me gustaría revisar este apartado en el proximo sprint porque me da la sensación de que no lo estoy haciendo bien.

**Comment by dsv0010** [comment]
-  attached revclopeznomemoria_conceptos_teoricos.pdf

Añado una revisión comentada
